name: "Create a virtual soundcard"
description: "A composite action to create a virtual soundcard on different operating systems."

runs:
  using: "composite"
  steps:
    - name: Create soundcard (linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        set -exo pipefail
        sudo apt update
        sudo apt install -y pulseaudio portaudio19-dev
        pulseaudio --check || pulseaudio --start
        pactl info
        pactl load-module module-null-sink sink_name=vspeaker sink_properties=device.description=virtual_speaker
        pactl load-module module-remap-source master=vspeaker.monitor source_name=vmic source_properties=device.description=virtual_mic
        pactl list short sinks
        pactl list short sources
    - name: Create soundcard (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        set -exo pipefail
        brew install blackhole-2ch switchaudio-osx
        SwitchAudioSource -s "BlackHole 2ch" -t input
        SwitchAudioSource -s "BlackHole 2ch" -t output
    - name: Get soundcard dependencies (windows)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/4.0/Scream4.0.zip -OutFile Scream4.0.zip
        Expand-Archive -Path Scream4.0.zip -DestinationPath Scream
        openssl req -batch -verbose -x509 -newkey rsa -keyout ScreamCertificate.pvk -out ScreamCertificate.cer -nodes -extensions v3_req
        openssl pkcs12 -export -nodes -in ScreamCertificate.cer -inkey ScreamCertificate.pvk -out ScreamCertificate.pfx -passout pass:
    - name: Setup MSVC Dev Cmd (windows)
      if: ${{ runner.os == 'Windows' }}
      uses: ilammy/msvc-dev-cmd@v1
    - name: Sign and Install Scream Driver (windows)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        signtool sign /v /fd SHA256 /f ScreamCertificate.pfx Scream\Install\driver\x64\Scream.cat
        Import-Certificate -FilePath ScreamCertificate.cer -CertStoreLocation Cert:\LocalMachine\root
        Import-Certificate -FilePath ScreamCertificate.cer -CertStoreLocation Cert:\LocalMachine\TrustedPublisher
        Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream
    - name: Create soundcard (windows)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: net start audiosrv
