name: publish
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install liblsl
        uses: ./.github/actions/install-liblsl
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Create virtual sound card
        uses: LABSN/sound-ci-helpers@v1
      - name: Install package
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip install --progress-bar off -e .[build,stubs]
      - name: Display system information
        run: stimuli sys-info --developer
      - name: Generate stub files
        run: python tools/stubgen.py
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN  }}
        run: |
          python -m build
          twine check --strict dist/*
          twine upload dist/*
